### ISSUE TITLE
Portal linking failed. Compass not linked?

### ISSUE THREAD

**Issue by b1bradders** [Pinaz993/ImmersiveTransit#1]
What does this mean?

**Comment by Pinaz993** [comment]
This means that while there is a compass in your offhand, the compass is not linked to a lodestone. If it was linked at one the, perhaps the lodestone has been broken.

I will attempt to be more clear about the error messages in the documentation.

**Comment by Pinaz993** [comment]
Error messages should be more clear now.

**Comment by b1bradders** [comment]
Thanks.
