### ISSUE TITLE
This data pack is hell.

### ISSUE THREAD

**Issue by b1bradders** [Pinaz993/ImmersiveTransit#2]
I can't get a 1x1 to link with 10x8, it makes the 10x8 at the location of the 1x1. I see why I was hesitant to come here when the people from Immersive Portals told me to use this.

**Comment by Pinaz993** [comment]
This datapack is meant to create portals that are the same size and shape. I do not know of any datapack or mod that can link between portals of different shape, such as between a 1x1 and a 10x8.

In addition, while the portal helper blocks would be able to link between portals of different scale, such as between a 10x10 and a 1x1, that  capability is out of the scope of Immersive Transit.
